FROM python:3.7

RUN mkdir /anti_fraud_socket
COPY _client.py /anti_fraud_socket/client.py
COPY requirements.txt /anti_fraud_socket/requirements.txt
WORKDIR /anti_fraud_socket

RUN pip install --upgrade pip && pip install -r requirements.txt